spring.application.name = foodDelivery

server.port = 8081

logging.level.org.hibernate=warn

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=pass@123
spring.jpa.show-sql=true

#logging.level.root=OFF

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20

spring.kafka.bootstrap-servers= localhost:9092
spring.kafka.consumer.group-id = order-group
spring.kafka.consumer.auto-offset-reset= earliest